### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dgudim** [gamemn02/Settings-Database-Provider#3]
Do you know any apps that use this? Would be interesting to know.

**Comment by gamemn02** [comment]
I think only our app Settings Database Editor published on Google Play.

**Comment by dgudim** [comment]
Why not on fdroid though? But still s nice app, that's a better experience than setedit

**Comment by gamemn02** [comment]
I don't think it is a wise step currently to opensource the app. But we may publish on another store that doesn't care much about the target SDK level.

**Comment by dgudim** [comment]
Got you.

**Comment by drogga** [comment]
@gamemn02 it seems like either your dev. [NetVor - Android Solutions] account was suspended by Google, you deleted it or just unpublished all of your 3 apps for some reason (unfortunately), now what, will you post them here, on f-droid or other places ? (I prefer here on GitHub)

I can see that you also have a site, but it's useless in its current state, because it only contains/has a link to SDE's PS page, nothing else.
The same for the other one here: https://github.com/gamemn02/gamemn02.github.io
